// <auto-generated>This is auto-generated code by DIS. Do not modify.</auto-generated>
using System.ComponentModel;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace Skyline.DataMiner.Scripting
{
public static class Parameter
{
	/// <summary>PID: 1 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int tokenapi_1 = 1;
	/// <summary>PID: 1 | Type: read</summary>
	public const int tokenapi = 1;
	/// <summary>PID: 5 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int authflag_5 = 5;
	/// <summary>PID: 5 | Type: read</summary>
	public const int authflag = 5;
	/// <summary>PID: 10 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int username_10 = 10;
	/// <summary>PID: 10 | Type: read</summary>
	public const int username = 10;
	/// <summary>PID: 11 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int password_11 = 11;
	/// <summary>PID: 11 | Type: read</summary>
	public const int password = 11;
	/// <summary>PID: 300 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int gettokenstatuscode_300 = 300;
	/// <summary>PID: 300 | Type: read</summary>
	public const int gettokenstatuscode = 300;
	/// <summary>PID: 301 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int gettokenresponse_301 = 301;
	/// <summary>PID: 301 | Type: read</summary>
	public const int gettokenresponse = 301;
	/// <summary>PID: 302 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int gettokenreuqestbody_302 = 302;
	/// <summary>PID: 302 | Type: read</summary>
	public const int gettokenreuqestbody = 302;
	/// <summary>PID: 303 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int getstatussystemcode_303 = 303;
	/// <summary>PID: 303 | Type: read</summary>
	public const int getstatussystemcode = 303;
	/// <summary>PID: 304 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int getsystemresponse_304 = 304;
	/// <summary>PID: 304 | Type: read</summary>
	public const int getsystemresponse = 304;
	/// <summary>PID: 305 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int getclientstatscode_305 = 305;
	/// <summary>PID: 305 | Type: read</summary>
	public const int getclientstatscode = 305;
	/// <summary>PID: 306 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int getclientstatsresponse_306 = 306;
	/// <summary>PID: 306 | Type: read</summary>
	public const int getclientstatsresponse = 306;
	/// <summary>PID: 307 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int getpartylinescode_307 = 307;
	/// <summary>PID: 307 | Type: read</summary>
	public const int getpartylinescode = 307;
	/// <summary>PID: 308 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int getpartylinesresponse_308 = 308;
	/// <summary>PID: 308 | Type: read</summary>
	public const int getpartylinesresponse = 308;
	/// <summary>PID: 309 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int getclientscode_309 = 309;
	/// <summary>PID: 309 | Type: read</summary>
	public const int getclientscode = 309;
	/// <summary>PID: 310 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int getclientsresponse_310 = 310;
	/// <summary>PID: 310 | Type: read</summary>
	public const int getclientsresponse = 310;
	public class Write
	{
		/// <summary>PID: 60 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int username_60 = 60;
		/// <summary>PID: 60 | Type: write</summary>
		public const int username = 60;
		/// <summary>PID: 61 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int password_61 = 61;
		/// <summary>PID: 61 | Type: write</summary>
		public const int password = 61;
	}
	public class Statussystem
	{
		/// <summary>PID: 1000</summary>
		public const int tablePid = 1000;
		/// <summary>IDX: 0</summary>
		public const int indexColumn = 0;
		/// <summary>PID: 1001</summary>
		public const int indexColumnPid = 1001;
		public class Pid
		{
			/// <summary>PID: 1001 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int statussystemname_1001 = 1001;
			/// <summary>PID: 1001 | Type: read</summary>
			public const int statussystemname = 1001;
			/// <summary>PID: 1002 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int statussystemtext_1002 = 1002;
			/// <summary>PID: 1002 | Type: read</summary>
			public const int statussystemtext = 1002;
			/// <summary>PID: 1003 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int statusSystemStatus_1003 = 1003;
			/// <summary>PID: 1003 | Type: read</summary>
			public const int statusSystemStatus = 1003;
			public class Write
			{
			}
		}
		public class Idx
		{
			/// <summary>IDX: 0 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int statussystemname_1001 = 0;
			/// <summary>IDX: 0 | Type: read</summary>
			public const int statussystemname = 0;
			/// <summary>IDX: 1 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int statussystemtext_1002 = 1;
			/// <summary>IDX: 1 | Type: read</summary>
			public const int statussystemtext = 1;
			/// <summary>IDX: 2 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int statusSystemStatus_1003 = 2;
			/// <summary>IDX: 2 | Type: read</summary>
			public const int statusSystemStatus = 2;
		}
	}
	public class Clientstatistics
	{
		/// <summary>PID: 2000</summary>
		public const int tablePid = 2000;
		/// <summary>IDX: 0</summary>
		public const int indexColumn = 0;
		/// <summary>PID: 2001</summary>
		public const int indexColumnPid = 2001;
		public class Pid
		{
			/// <summary>PID: 2001 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int clientstatisticsid_2001 = 2001;
			/// <summary>PID: 2001 | Type: read</summary>
			public const int clientstatisticsid = 2001;
			/// <summary>PID: 2002 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int clientstatisticsconnectionstatus_2002 = 2002;
			/// <summary>PID: 2002 | Type: read</summary>
			public const int clientstatisticsconnectionstatus = 2002;
			/// <summary>PID: 2003 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int clientstatisticsclientid_2003 = 2003;
			/// <summary>PID: 2003 | Type: read</summary>
			public const int clientstatisticsclientid = 2003;
			/// <summary>PID: 2004 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int clientstatisticsclientnumber_2004 = 2004;
			/// <summary>PID: 2004 | Type: read</summary>
			public const int clientstatisticsclientnumber = 2004;
			/// <summary>PID: 2005 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int clientstatisticsipaddress_2005 = 2005;
			/// <summary>PID: 2005 | Type: read</summary>
			public const int clientstatisticsipaddress = 2005;
			/// <summary>PID: 2006 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int clientstatisticsconnectionstateduration_2006 = 2006;
			/// <summary>PID: 2006 | Type: read</summary>
			public const int clientstatisticsconnectionstateduration = 2006;
			/// <summary>PID: 2007 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int clientstatisticsdisconnectcount_2007 = 2007;
			/// <summary>PID: 2007 | Type: read</summary>
			public const int clientstatisticsdisconnectcount = 2007;
			/// <summary>PID: 2008 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int clientstatisticsdisconnectstateduration_2008 = 2008;
			/// <summary>PID: 2008 | Type: read</summary>
			public const int clientstatisticsdisconnectstateduration = 2008;
			public class Write
			{
			}
		}
		public class Idx
		{
			/// <summary>IDX: 0 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int clientstatisticsid_2001 = 0;
			/// <summary>IDX: 0 | Type: read</summary>
			public const int clientstatisticsid = 0;
			/// <summary>IDX: 1 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int clientstatisticsconnectionstatus_2002 = 1;
			/// <summary>IDX: 1 | Type: read</summary>
			public const int clientstatisticsconnectionstatus = 1;
			/// <summary>IDX: 2 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int clientstatisticsclientid_2003 = 2;
			/// <summary>IDX: 2 | Type: read</summary>
			public const int clientstatisticsclientid = 2;
			/// <summary>IDX: 3 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int clientstatisticsclientnumber_2004 = 3;
			/// <summary>IDX: 3 | Type: read</summary>
			public const int clientstatisticsclientnumber = 3;
			/// <summary>IDX: 4 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int clientstatisticsipaddress_2005 = 4;
			/// <summary>IDX: 4 | Type: read</summary>
			public const int clientstatisticsipaddress = 4;
			/// <summary>IDX: 5 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int clientstatisticsconnectionstateduration_2006 = 5;
			/// <summary>IDX: 5 | Type: read</summary>
			public const int clientstatisticsconnectionstateduration = 5;
			/// <summary>IDX: 6 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int clientstatisticsdisconnectcount_2007 = 6;
			/// <summary>IDX: 6 | Type: read</summary>
			public const int clientstatisticsdisconnectcount = 6;
			/// <summary>IDX: 7 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int clientstatisticsdisconnectstateduration_2008 = 7;
			/// <summary>IDX: 7 | Type: read</summary>
			public const int clientstatisticsdisconnectstateduration = 7;
		}
	}
	public class Partylines
	{
		/// <summary>PID: 3000</summary>
		public const int tablePid = 3000;
		/// <summary>IDX: 0</summary>
		public const int indexColumn = 0;
		/// <summary>PID: 3001</summary>
		public const int indexColumnPid = 3001;
		public class Pid
		{
			/// <summary>PID: 3001 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int partylinesid_3001 = 3001;
			/// <summary>PID: 3001 | Type: read</summary>
			public const int partylinesid = 3001;
			/// <summary>PID: 3002 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int partylineslabelcategory_3002 = 3002;
			/// <summary>PID: 3002 | Type: read</summary>
			public const int partylineslabelcategory = 3002;
			/// <summary>PID: 3003 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int partylineslabelindex_3003 = 3003;
			/// <summary>PID: 3003 | Type: read</summary>
			public const int partylineslabelindex = 3003;
			/// <summary>PID: 3004 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int partylinesselectorname_3004 = 3004;
			/// <summary>PID: 3004 | Type: read</summary>
			public const int partylinesselectorname = 3004;
			/// <summary>PID: 3005 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int partylinesimage_3005 = 3005;
			/// <summary>PID: 3005 | Type: read</summary>
			public const int partylinesimage = 3005;
			public class Write
			{
			}
		}
		public class Idx
		{
			/// <summary>IDX: 0 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int partylinesid_3001 = 0;
			/// <summary>IDX: 0 | Type: read</summary>
			public const int partylinesid = 0;
			/// <summary>IDX: 1 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int partylineslabelcategory_3002 = 1;
			/// <summary>IDX: 1 | Type: read</summary>
			public const int partylineslabelcategory = 1;
			/// <summary>IDX: 2 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int partylineslabelindex_3003 = 2;
			/// <summary>IDX: 2 | Type: read</summary>
			public const int partylineslabelindex = 2;
			/// <summary>IDX: 3 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int partylinesselectorname_3004 = 3;
			/// <summary>IDX: 3 | Type: read</summary>
			public const int partylinesselectorname = 3;
			/// <summary>IDX: 4 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int partylinesimage_3005 = 4;
			/// <summary>IDX: 4 | Type: read</summary>
			public const int partylinesimage = 4;
		}
	}
	public class Clients
	{
		/// <summary>PID: 4000</summary>
		public const int tablePid = 4000;
		/// <summary>IDX: 0</summary>
		public const int indexColumn = 0;
		/// <summary>PID: 4001</summary>
		public const int indexColumnPid = 4001;
		public class Pid
		{
			/// <summary>PID: 4001 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int clientid_4001 = 4001;
			/// <summary>PID: 4001 | Type: read</summary>
			public const int clientid = 4001;
			/// <summary>PID: 4002 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int clientcategory_4002 = 4002;
			/// <summary>PID: 4002 | Type: read</summary>
			public const int clientcategory = 4002;
			/// <summary>PID: 4003 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int clientlabelindex_4003 = 4003;
			/// <summary>PID: 4003 | Type: read</summary>
			public const int clientlabelindex = 4003;
			/// <summary>PID: 4004 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int clientlabeltype_4004 = 4004;
			/// <summary>PID: 4004 | Type: read</summary>
			public const int clientlabeltype = 4004;
			/// <summary>PID: 4005 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int clientselectorname_4005 = 4005;
			/// <summary>PID: 4005 | Type: read</summary>
			public const int clientselectorname = 4005;
			/// <summary>PID: 4006 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int clientimage_4006 = 4006;
			/// <summary>PID: 4006 | Type: read</summary>
			public const int clientimage = 4006;
			/// <summary>PID: 4007 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int clientlastconnectiontime_4007 = 4007;
			/// <summary>PID: 4007 | Type: read</summary>
			public const int clientlastconnectiontime = 4007;
			public class Write
			{
			}
		}
		public class Idx
		{
			/// <summary>IDX: 0 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int clientid_4001 = 0;
			/// <summary>IDX: 0 | Type: read</summary>
			public const int clientid = 0;
			/// <summary>IDX: 1 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int clientcategory_4002 = 1;
			/// <summary>IDX: 1 | Type: read</summary>
			public const int clientcategory = 1;
			/// <summary>IDX: 2 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int clientlabelindex_4003 = 2;
			/// <summary>IDX: 2 | Type: read</summary>
			public const int clientlabelindex = 2;
			/// <summary>IDX: 3 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int clientlabeltype_4004 = 3;
			/// <summary>IDX: 3 | Type: read</summary>
			public const int clientlabeltype = 3;
			/// <summary>IDX: 4 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int clientselectorname_4005 = 4;
			/// <summary>IDX: 4 | Type: read</summary>
			public const int clientselectorname = 4;
			/// <summary>IDX: 5 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int clientimage_4006 = 5;
			/// <summary>IDX: 5 | Type: read</summary>
			public const int clientimage = 5;
			/// <summary>IDX: 6 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int clientlastconnectiontime_4007 = 6;
			/// <summary>IDX: 6 | Type: read</summary>
			public const int clientlastconnectiontime = 6;
		}
	}
}
public class WriteParameters
{
	/// <summary>PID: 60  | Type: write</summary>
	public System.Object Username {get { return Protocol.GetParameter(60); }set { Protocol.SetParameter(60, value); }}
	/// <summary>PID: 61  | Type: write</summary>
	public System.Object Password {get { return Protocol.GetParameter(61); }set { Protocol.SetParameter(61, value); }}
	public SLProtocolExt Protocol;
	public WriteParameters(SLProtocolExt protocol)
	{
		Protocol = protocol;
	}
}
public interface SLProtocolExt : SLProtocol
{
	/// <summary>PID: 1000</summary>
	StatussystemQActionTable statussystem { get; set; }
	/// <summary>PID: 2000</summary>
	ClientstatisticsQActionTable clientstatistics { get; set; }
	/// <summary>PID: 3000</summary>
	PartylinesQActionTable partylines { get; set; }
	/// <summary>PID: 4000</summary>
	ClientsQActionTable clients { get; set; }
	object Tokenapi_1 { get; set; }
	object Tokenapi { get; set; }
	object Afterstartup_dummy { get; set; }
	object Authflag_5 { get; set; }
	object Authflag { get; set; }
	object Username_10 { get; set; }
	object Username { get; set; }
	object Password_11 { get; set; }
	object Password { get; set; }
	object Username_60 { get; set; }
	object Password_61 { get; set; }
	object Gettokenstatuscode_300 { get; set; }
	object Gettokenstatuscode { get; set; }
	object Gettokenresponse_301 { get; set; }
	object Gettokenresponse { get; set; }
	object Gettokenreuqestbody_302 { get; set; }
	object Gettokenreuqestbody { get; set; }
	object Getstatussystemcode_303 { get; set; }
	object Getstatussystemcode { get; set; }
	object Getsystemresponse_304 { get; set; }
	object Getsystemresponse { get; set; }
	object Getclientstatscode_305 { get; set; }
	object Getclientstatscode { get; set; }
	object Getclientstatsresponse_306 { get; set; }
	object Getclientstatsresponse { get; set; }
	object Getpartylinescode_307 { get; set; }
	object Getpartylinescode { get; set; }
	object Getpartylinesresponse_308 { get; set; }
	object Getpartylinesresponse { get; set; }
	object Getclientscode_309 { get; set; }
	object Getclientscode { get; set; }
	object Getclientsresponse_310 { get; set; }
	object Getclientsresponse { get; set; }
	object Statussystemname_1001 { get; set; }
	object Statussystemname { get; set; }
	object Statussystemtext_1002 { get; set; }
	object Statussystemtext { get; set; }
	object StatusSystemStatus_1003 { get; set; }
	object StatusSystemStatus { get; set; }
	object Clientstatisticsid_2001 { get; set; }
	object Clientstatisticsid { get; set; }
	object Clientstatisticsconnectionstatus_2002 { get; set; }
	object Clientstatisticsconnectionstatus { get; set; }
	object Clientstatisticsclientid_2003 { get; set; }
	object Clientstatisticsclientid { get; set; }
	object Clientstatisticsclientnumber_2004 { get; set; }
	object Clientstatisticsclientnumber { get; set; }
	object Clientstatisticsipaddress_2005 { get; set; }
	object Clientstatisticsipaddress { get; set; }
	object Clientstatisticsconnectionstateduration_2006 { get; set; }
	object Clientstatisticsconnectionstateduration { get; set; }
	object Clientstatisticsdisconnectcount_2007 { get; set; }
	object Clientstatisticsdisconnectcount { get; set; }
	object Clientstatisticsdisconnectstateduration_2008 { get; set; }
	object Clientstatisticsdisconnectstateduration { get; set; }
	object Partylinesid_3001 { get; set; }
	object Partylinesid { get; set; }
	object Partylineslabelcategory_3002 { get; set; }
	object Partylineslabelcategory { get; set; }
	object Partylineslabelindex_3003 { get; set; }
	object Partylineslabelindex { get; set; }
	object Partylinesselectorname_3004 { get; set; }
	object Partylinesselectorname { get; set; }
	object Partylinesimage_3005 { get; set; }
	object Partylinesimage { get; set; }
	object Clientid_4001 { get; set; }
	object Clientid { get; set; }
	object Clientcategory_4002 { get; set; }
	object Clientcategory { get; set; }
	object Clientlabelindex_4003 { get; set; }
	object Clientlabelindex { get; set; }
	object Clientlabeltype_4004 { get; set; }
	object Clientlabeltype { get; set; }
	object Clientselectorname_4005 { get; set; }
	object Clientselectorname { get; set; }
	object Clientimage_4006 { get; set; }
	object Clientimage { get; set; }
	object Clientlastconnectiontime_4007 { get; set; }
	object Clientlastconnectiontime { get; set; }
	WriteParameters Write { get; set; }
}
public class ConcreteSLProtocolExt : ConcreteSLProtocol, SLProtocolExt
{
	/// <summary>PID: 1000</summary>
	public StatussystemQActionTable statussystem { get; set; }
	/// <summary>PID: 2000</summary>
	public ClientstatisticsQActionTable clientstatistics { get; set; }
	/// <summary>PID: 3000</summary>
	public PartylinesQActionTable partylines { get; set; }
	/// <summary>PID: 4000</summary>
	public ClientsQActionTable clients { get; set; }
	/// <summary>PID: 1  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Tokenapi_1 {get { return GetParameter(1); }set { SetParameter(1, value); }}
	/// <summary>PID: 1  | Type: read</summary>
	public System.Object Tokenapi {get { return GetParameter(1); }set { SetParameter(1, value); }}
	/// <summary>PID: 2  | Type: dummy</summary>
	public System.Object Afterstartup_dummy {get { return GetParameter(2); }set { SetParameter(2, value); }}
	/// <summary>PID: 5  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Authflag_5 {get { return GetParameter(5); }set { SetParameter(5, value); }}
	/// <summary>PID: 5  | Type: read</summary>
	public System.Object Authflag {get { return GetParameter(5); }set { SetParameter(5, value); }}
	/// <summary>PID: 10  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Username_10 {get { return GetParameter(10); }set { SetParameter(10, value); }}
	/// <summary>PID: 10  | Type: read</summary>
	public System.Object Username {get { return GetParameter(10); }set { SetParameter(10, value); }}
	/// <summary>PID: 11  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Password_11 {get { return GetParameter(11); }set { SetParameter(11, value); }}
	/// <summary>PID: 11  | Type: read</summary>
	public System.Object Password {get { return GetParameter(11); }set { SetParameter(11, value); }}
	/// <summary>PID: 60  | Type: write</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Username_60 {get { return GetParameter(60); }set { SetParameter(60, value); }}
	/// <summary>PID: 61  | Type: write</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Password_61 {get { return GetParameter(61); }set { SetParameter(61, value); }}
	/// <summary>PID: 300  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Gettokenstatuscode_300 {get { return GetParameter(300); }set { SetParameter(300, value); }}
	/// <summary>PID: 300  | Type: read</summary>
	public System.Object Gettokenstatuscode {get { return GetParameter(300); }set { SetParameter(300, value); }}
	/// <summary>PID: 301  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Gettokenresponse_301 {get { return GetParameter(301); }set { SetParameter(301, value); }}
	/// <summary>PID: 301  | Type: read</summary>
	public System.Object Gettokenresponse {get { return GetParameter(301); }set { SetParameter(301, value); }}
	/// <summary>PID: 302  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Gettokenreuqestbody_302 {get { return GetParameter(302); }set { SetParameter(302, value); }}
	/// <summary>PID: 302  | Type: read</summary>
	public System.Object Gettokenreuqestbody {get { return GetParameter(302); }set { SetParameter(302, value); }}
	/// <summary>PID: 303  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Getstatussystemcode_303 {get { return GetParameter(303); }set { SetParameter(303, value); }}
	/// <summary>PID: 303  | Type: read</summary>
	public System.Object Getstatussystemcode {get { return GetParameter(303); }set { SetParameter(303, value); }}
	/// <summary>PID: 304  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Getsystemresponse_304 {get { return GetParameter(304); }set { SetParameter(304, value); }}
	/// <summary>PID: 304  | Type: read</summary>
	public System.Object Getsystemresponse {get { return GetParameter(304); }set { SetParameter(304, value); }}
	/// <summary>PID: 305  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Getclientstatscode_305 {get { return GetParameter(305); }set { SetParameter(305, value); }}
	/// <summary>PID: 305  | Type: read</summary>
	public System.Object Getclientstatscode {get { return GetParameter(305); }set { SetParameter(305, value); }}
	/// <summary>PID: 306  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Getclientstatsresponse_306 {get { return GetParameter(306); }set { SetParameter(306, value); }}
	/// <summary>PID: 306  | Type: read</summary>
	public System.Object Getclientstatsresponse {get { return GetParameter(306); }set { SetParameter(306, value); }}
	/// <summary>PID: 307  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Getpartylinescode_307 {get { return GetParameter(307); }set { SetParameter(307, value); }}
	/// <summary>PID: 307  | Type: read</summary>
	public System.Object Getpartylinescode {get { return GetParameter(307); }set { SetParameter(307, value); }}
	/// <summary>PID: 308  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Getpartylinesresponse_308 {get { return GetParameter(308); }set { SetParameter(308, value); }}
	/// <summary>PID: 308  | Type: read</summary>
	public System.Object Getpartylinesresponse {get { return GetParameter(308); }set { SetParameter(308, value); }}
	/// <summary>PID: 309  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Getclientscode_309 {get { return GetParameter(309); }set { SetParameter(309, value); }}
	/// <summary>PID: 309  | Type: read</summary>
	public System.Object Getclientscode {get { return GetParameter(309); }set { SetParameter(309, value); }}
	/// <summary>PID: 310  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Getclientsresponse_310 {get { return GetParameter(310); }set { SetParameter(310, value); }}
	/// <summary>PID: 310  | Type: read</summary>
	public System.Object Getclientsresponse {get { return GetParameter(310); }set { SetParameter(310, value); }}
	/// <summary>PID: 1001  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Statussystemname_1001 {get { return GetParameter(1001); }set { SetParameter(1001, value); }}
	/// <summary>PID: 1001  | Type: read</summary>
	public System.Object Statussystemname {get { return GetParameter(1001); }set { SetParameter(1001, value); }}
	/// <summary>PID: 1002  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Statussystemtext_1002 {get { return GetParameter(1002); }set { SetParameter(1002, value); }}
	/// <summary>PID: 1002  | Type: read</summary>
	public System.Object Statussystemtext {get { return GetParameter(1002); }set { SetParameter(1002, value); }}
	/// <summary>PID: 1003  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object StatusSystemStatus_1003 {get { return GetParameter(1003); }set { SetParameter(1003, value); }}
	/// <summary>PID: 1003  | Type: read</summary>
	public System.Object StatusSystemStatus {get { return GetParameter(1003); }set { SetParameter(1003, value); }}
	/// <summary>PID: 2001  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Clientstatisticsid_2001 {get { return GetParameter(2001); }set { SetParameter(2001, value); }}
	/// <summary>PID: 2001  | Type: read</summary>
	public System.Object Clientstatisticsid {get { return GetParameter(2001); }set { SetParameter(2001, value); }}
	/// <summary>PID: 2002  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Clientstatisticsconnectionstatus_2002 {get { return GetParameter(2002); }set { SetParameter(2002, value); }}
	/// <summary>PID: 2002  | Type: read</summary>
	public System.Object Clientstatisticsconnectionstatus {get { return GetParameter(2002); }set { SetParameter(2002, value); }}
	/// <summary>PID: 2003  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Clientstatisticsclientid_2003 {get { return GetParameter(2003); }set { SetParameter(2003, value); }}
	/// <summary>PID: 2003  | Type: read</summary>
	public System.Object Clientstatisticsclientid {get { return GetParameter(2003); }set { SetParameter(2003, value); }}
	/// <summary>PID: 2004  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Clientstatisticsclientnumber_2004 {get { return GetParameter(2004); }set { SetParameter(2004, value); }}
	/// <summary>PID: 2004  | Type: read</summary>
	public System.Object Clientstatisticsclientnumber {get { return GetParameter(2004); }set { SetParameter(2004, value); }}
	/// <summary>PID: 2005  | Type: read | EXCEPTIONS: N/A = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Clientstatisticsipaddress_2005 {get { return GetParameter(2005); }set { SetParameter(2005, value); }}
	/// <summary>PID: 2005  | Type: read | EXCEPTIONS: N/A = -1</summary>
	public System.Object Clientstatisticsipaddress {get { return GetParameter(2005); }set { SetParameter(2005, value); }}
	/// <summary>PID: 2006  | Type: read | EXCEPTIONS: N/A = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Clientstatisticsconnectionstateduration_2006 {get { return GetParameter(2006); }set { SetParameter(2006, value); }}
	/// <summary>PID: 2006  | Type: read | EXCEPTIONS: N/A = -1</summary>
	public System.Object Clientstatisticsconnectionstateduration {get { return GetParameter(2006); }set { SetParameter(2006, value); }}
	/// <summary>PID: 2007  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Clientstatisticsdisconnectcount_2007 {get { return GetParameter(2007); }set { SetParameter(2007, value); }}
	/// <summary>PID: 2007  | Type: read</summary>
	public System.Object Clientstatisticsdisconnectcount {get { return GetParameter(2007); }set { SetParameter(2007, value); }}
	/// <summary>PID: 2008  | Type: read | EXCEPTIONS: N/A = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Clientstatisticsdisconnectstateduration_2008 {get { return GetParameter(2008); }set { SetParameter(2008, value); }}
	/// <summary>PID: 2008  | Type: read | EXCEPTIONS: N/A = -1</summary>
	public System.Object Clientstatisticsdisconnectstateduration {get { return GetParameter(2008); }set { SetParameter(2008, value); }}
	/// <summary>PID: 3001  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Partylinesid_3001 {get { return GetParameter(3001); }set { SetParameter(3001, value); }}
	/// <summary>PID: 3001  | Type: read</summary>
	public System.Object Partylinesid {get { return GetParameter(3001); }set { SetParameter(3001, value); }}
	/// <summary>PID: 3002  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Partylineslabelcategory_3002 {get { return GetParameter(3002); }set { SetParameter(3002, value); }}
	/// <summary>PID: 3002  | Type: read</summary>
	public System.Object Partylineslabelcategory {get { return GetParameter(3002); }set { SetParameter(3002, value); }}
	/// <summary>PID: 3003  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Partylineslabelindex_3003 {get { return GetParameter(3003); }set { SetParameter(3003, value); }}
	/// <summary>PID: 3003  | Type: read</summary>
	public System.Object Partylineslabelindex {get { return GetParameter(3003); }set { SetParameter(3003, value); }}
	/// <summary>PID: 3004  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Partylinesselectorname_3004 {get { return GetParameter(3004); }set { SetParameter(3004, value); }}
	/// <summary>PID: 3004  | Type: read</summary>
	public System.Object Partylinesselectorname {get { return GetParameter(3004); }set { SetParameter(3004, value); }}
	/// <summary>PID: 3005  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Partylinesimage_3005 {get { return GetParameter(3005); }set { SetParameter(3005, value); }}
	/// <summary>PID: 3005  | Type: read</summary>
	public System.Object Partylinesimage {get { return GetParameter(3005); }set { SetParameter(3005, value); }}
	/// <summary>PID: 4001  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Clientid_4001 {get { return GetParameter(4001); }set { SetParameter(4001, value); }}
	/// <summary>PID: 4001  | Type: read</summary>
	public System.Object Clientid {get { return GetParameter(4001); }set { SetParameter(4001, value); }}
	/// <summary>PID: 4002  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Clientcategory_4002 {get { return GetParameter(4002); }set { SetParameter(4002, value); }}
	/// <summary>PID: 4002  | Type: read</summary>
	public System.Object Clientcategory {get { return GetParameter(4002); }set { SetParameter(4002, value); }}
	/// <summary>PID: 4003  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Clientlabelindex_4003 {get { return GetParameter(4003); }set { SetParameter(4003, value); }}
	/// <summary>PID: 4003  | Type: read</summary>
	public System.Object Clientlabelindex {get { return GetParameter(4003); }set { SetParameter(4003, value); }}
	/// <summary>PID: 4004  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Clientlabeltype_4004 {get { return GetParameter(4004); }set { SetParameter(4004, value); }}
	/// <summary>PID: 4004  | Type: read</summary>
	public System.Object Clientlabeltype {get { return GetParameter(4004); }set { SetParameter(4004, value); }}
	/// <summary>PID: 4005  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Clientselectorname_4005 {get { return GetParameter(4005); }set { SetParameter(4005, value); }}
	/// <summary>PID: 4005  | Type: read</summary>
	public System.Object Clientselectorname {get { return GetParameter(4005); }set { SetParameter(4005, value); }}
	/// <summary>PID: 4006  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Clientimage_4006 {get { return GetParameter(4006); }set { SetParameter(4006, value); }}
	/// <summary>PID: 4006  | Type: read</summary>
	public System.Object Clientimage {get { return GetParameter(4006); }set { SetParameter(4006, value); }}
	/// <summary>PID: 4007  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Clientlastconnectiontime_4007 {get { return GetParameter(4007); }set { SetParameter(4007, value); }}
	/// <summary>PID: 4007  | Type: read</summary>
	public System.Object Clientlastconnectiontime {get { return GetParameter(4007); }set { SetParameter(4007, value); }}
	public WriteParameters Write { get; set; }
	public ConcreteSLProtocolExt()
	{
		statussystem = new StatussystemQActionTable(this, 1000, "statussystem");
		clientstatistics = new ClientstatisticsQActionTable(this, 2000, "clientstatistics");
		partylines = new PartylinesQActionTable(this, 3000, "partylines");
		clients = new ClientsQActionTable(this, 4000, "clients");
		Write = new WriteParameters(this);
	}
}
/// <summary>IDX: 0</summary>
public class StatussystemQActionTable : QActionTable, IEnumerable<StatussystemQActionRow>
{
	public StatussystemQActionTable(SLProtocol protocol, int tableId, string tableName) : base(protocol, tableId, tableName) { }
	IEnumerator IEnumerable.GetEnumerator() { return (IEnumerator) GetEnumerator(); }
	public IEnumerator<StatussystemQActionRow> GetEnumerator() { return new QActionTableEnumerator<StatussystemQActionRow>(this); }
}
/// <summary>IDX: 0</summary>
public class ClientstatisticsQActionTable : QActionTable, IEnumerable<ClientstatisticsQActionRow>
{
	public ClientstatisticsQActionTable(SLProtocol protocol, int tableId, string tableName) : base(protocol, tableId, tableName) { }
	IEnumerator IEnumerable.GetEnumerator() { return (IEnumerator) GetEnumerator(); }
	public IEnumerator<ClientstatisticsQActionRow> GetEnumerator() { return new QActionTableEnumerator<ClientstatisticsQActionRow>(this); }
}
/// <summary>IDX: 0</summary>
public class PartylinesQActionTable : QActionTable, IEnumerable<PartylinesQActionRow>
{
	public PartylinesQActionTable(SLProtocol protocol, int tableId, string tableName) : base(protocol, tableId, tableName) { }
	IEnumerator IEnumerable.GetEnumerator() { return (IEnumerator) GetEnumerator(); }
	public IEnumerator<PartylinesQActionRow> GetEnumerator() { return new QActionTableEnumerator<PartylinesQActionRow>(this); }
}
/// <summary>IDX: 0</summary>
public class ClientsQActionTable : QActionTable, IEnumerable<ClientsQActionRow>
{
	public ClientsQActionTable(SLProtocol protocol, int tableId, string tableName) : base(protocol, tableId, tableName) { }
	IEnumerator IEnumerable.GetEnumerator() { return (IEnumerator) GetEnumerator(); }
	public IEnumerator<ClientsQActionRow> GetEnumerator() { return new QActionTableEnumerator<ClientsQActionRow>(this); }
}
/// <summary>IDX: 0</summary>
public class StatussystemQActionRow : QActionTableRow
{
	/// <summary>PID: 1001 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Statussystemname_1001 { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 1001 | Type: read</summary>
	public System.Object Statussystemname { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 1002 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Statussystemtext_1002 { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 1002 | Type: read</summary>
	public System.Object Statussystemtext { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 1003 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object StatusSystemStatus_1003 { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	/// <summary>PID: 1003 | Type: read</summary>
	public System.Object StatusSystemStatus { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	public StatussystemQActionRow() : base(0, 3) { }
	public StatussystemQActionRow(System.Object[] oRow) : base(0, 3, oRow) { }
	public static implicit operator StatussystemQActionRow(System.Object[] source) { return new StatussystemQActionRow(source); }
	public static implicit operator System.Object[](StatussystemQActionRow source) { return source.ToObjectArray(); }
}
/// <summary>IDX: 0</summary>
public class ClientstatisticsQActionRow : QActionTableRow
{
	/// <summary>PID: 2001 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Clientstatisticsid_2001 { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 2001 | Type: read</summary>
	public System.Object Clientstatisticsid { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 2002 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Clientstatisticsconnectionstatus_2002 { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 2002 | Type: read</summary>
	public System.Object Clientstatisticsconnectionstatus { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 2003 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Clientstatisticsclientid_2003 { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	/// <summary>PID: 2003 | Type: read</summary>
	public System.Object Clientstatisticsclientid { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	/// <summary>PID: 2004 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Clientstatisticsclientnumber_2004 { get { if (base.Columns.ContainsKey(3)) { return base.Columns[3]; } else { return null; } } set { if (base.Columns.ContainsKey(3)) { base.Columns[3] = value; } else { base.Columns.Add(3, value); } } }
	/// <summary>PID: 2004 | Type: read</summary>
	public System.Object Clientstatisticsclientnumber { get { if (base.Columns.ContainsKey(3)) { return base.Columns[3]; } else { return null; } } set { if (base.Columns.ContainsKey(3)) { base.Columns[3] = value; } else { base.Columns.Add(3, value); } } }
	/// <summary>PID: 2005 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Clientstatisticsipaddress_2005 { get { if (base.Columns.ContainsKey(4)) { return base.Columns[4]; } else { return null; } } set { if (base.Columns.ContainsKey(4)) { base.Columns[4] = value; } else { base.Columns.Add(4, value); } } }
	/// <summary>PID: 2005 | Type: read</summary>
	public System.Object Clientstatisticsipaddress { get { if (base.Columns.ContainsKey(4)) { return base.Columns[4]; } else { return null; } } set { if (base.Columns.ContainsKey(4)) { base.Columns[4] = value; } else { base.Columns.Add(4, value); } } }
	/// <summary>PID: 2006 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Clientstatisticsconnectionstateduration_2006 { get { if (base.Columns.ContainsKey(5)) { return base.Columns[5]; } else { return null; } } set { if (base.Columns.ContainsKey(5)) { base.Columns[5] = value; } else { base.Columns.Add(5, value); } } }
	/// <summary>PID: 2006 | Type: read</summary>
	public System.Object Clientstatisticsconnectionstateduration { get { if (base.Columns.ContainsKey(5)) { return base.Columns[5]; } else { return null; } } set { if (base.Columns.ContainsKey(5)) { base.Columns[5] = value; } else { base.Columns.Add(5, value); } } }
	/// <summary>PID: 2007 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Clientstatisticsdisconnectcount_2007 { get { if (base.Columns.ContainsKey(6)) { return base.Columns[6]; } else { return null; } } set { if (base.Columns.ContainsKey(6)) { base.Columns[6] = value; } else { base.Columns.Add(6, value); } } }
	/// <summary>PID: 2007 | Type: read</summary>
	public System.Object Clientstatisticsdisconnectcount { get { if (base.Columns.ContainsKey(6)) { return base.Columns[6]; } else { return null; } } set { if (base.Columns.ContainsKey(6)) { base.Columns[6] = value; } else { base.Columns.Add(6, value); } } }
	/// <summary>PID: 2008 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Clientstatisticsdisconnectstateduration_2008 { get { if (base.Columns.ContainsKey(7)) { return base.Columns[7]; } else { return null; } } set { if (base.Columns.ContainsKey(7)) { base.Columns[7] = value; } else { base.Columns.Add(7, value); } } }
	/// <summary>PID: 2008 | Type: read</summary>
	public System.Object Clientstatisticsdisconnectstateduration { get { if (base.Columns.ContainsKey(7)) { return base.Columns[7]; } else { return null; } } set { if (base.Columns.ContainsKey(7)) { base.Columns[7] = value; } else { base.Columns.Add(7, value); } } }
	public ClientstatisticsQActionRow() : base(0, 8) { }
	public ClientstatisticsQActionRow(System.Object[] oRow) : base(0, 8, oRow) { }
	public static implicit operator ClientstatisticsQActionRow(System.Object[] source) { return new ClientstatisticsQActionRow(source); }
	public static implicit operator System.Object[](ClientstatisticsQActionRow source) { return source.ToObjectArray(); }
}
/// <summary>IDX: 0</summary>
public class PartylinesQActionRow : QActionTableRow
{
	/// <summary>PID: 3001 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Partylinesid_3001 { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 3001 | Type: read</summary>
	public System.Object Partylinesid { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 3002 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Partylineslabelcategory_3002 { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 3002 | Type: read</summary>
	public System.Object Partylineslabelcategory { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 3003 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Partylineslabelindex_3003 { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	/// <summary>PID: 3003 | Type: read</summary>
	public System.Object Partylineslabelindex { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	/// <summary>PID: 3004 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Partylinesselectorname_3004 { get { if (base.Columns.ContainsKey(3)) { return base.Columns[3]; } else { return null; } } set { if (base.Columns.ContainsKey(3)) { base.Columns[3] = value; } else { base.Columns.Add(3, value); } } }
	/// <summary>PID: 3004 | Type: read</summary>
	public System.Object Partylinesselectorname { get { if (base.Columns.ContainsKey(3)) { return base.Columns[3]; } else { return null; } } set { if (base.Columns.ContainsKey(3)) { base.Columns[3] = value; } else { base.Columns.Add(3, value); } } }
	/// <summary>PID: 3005 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Partylinesimage_3005 { get { if (base.Columns.ContainsKey(4)) { return base.Columns[4]; } else { return null; } } set { if (base.Columns.ContainsKey(4)) { base.Columns[4] = value; } else { base.Columns.Add(4, value); } } }
	/// <summary>PID: 3005 | Type: read</summary>
	public System.Object Partylinesimage { get { if (base.Columns.ContainsKey(4)) { return base.Columns[4]; } else { return null; } } set { if (base.Columns.ContainsKey(4)) { base.Columns[4] = value; } else { base.Columns.Add(4, value); } } }
	public PartylinesQActionRow() : base(0, 5) { }
	public PartylinesQActionRow(System.Object[] oRow) : base(0, 5, oRow) { }
	public static implicit operator PartylinesQActionRow(System.Object[] source) { return new PartylinesQActionRow(source); }
	public static implicit operator System.Object[](PartylinesQActionRow source) { return source.ToObjectArray(); }
}
/// <summary>IDX: 0</summary>
public class ClientsQActionRow : QActionTableRow
{
	/// <summary>PID: 4001 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Clientid_4001 { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 4001 | Type: read</summary>
	public System.Object Clientid { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 4002 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Clientcategory_4002 { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 4002 | Type: read</summary>
	public System.Object Clientcategory { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 4003 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Clientlabelindex_4003 { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	/// <summary>PID: 4003 | Type: read</summary>
	public System.Object Clientlabelindex { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	/// <summary>PID: 4004 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Clientlabeltype_4004 { get { if (base.Columns.ContainsKey(3)) { return base.Columns[3]; } else { return null; } } set { if (base.Columns.ContainsKey(3)) { base.Columns[3] = value; } else { base.Columns.Add(3, value); } } }
	/// <summary>PID: 4004 | Type: read</summary>
	public System.Object Clientlabeltype { get { if (base.Columns.ContainsKey(3)) { return base.Columns[3]; } else { return null; } } set { if (base.Columns.ContainsKey(3)) { base.Columns[3] = value; } else { base.Columns.Add(3, value); } } }
	/// <summary>PID: 4005 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Clientselectorname_4005 { get { if (base.Columns.ContainsKey(4)) { return base.Columns[4]; } else { return null; } } set { if (base.Columns.ContainsKey(4)) { base.Columns[4] = value; } else { base.Columns.Add(4, value); } } }
	/// <summary>PID: 4005 | Type: read</summary>
	public System.Object Clientselectorname { get { if (base.Columns.ContainsKey(4)) { return base.Columns[4]; } else { return null; } } set { if (base.Columns.ContainsKey(4)) { base.Columns[4] = value; } else { base.Columns.Add(4, value); } } }
	/// <summary>PID: 4006 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Clientimage_4006 { get { if (base.Columns.ContainsKey(5)) { return base.Columns[5]; } else { return null; } } set { if (base.Columns.ContainsKey(5)) { base.Columns[5] = value; } else { base.Columns.Add(5, value); } } }
	/// <summary>PID: 4006 | Type: read</summary>
	public System.Object Clientimage { get { if (base.Columns.ContainsKey(5)) { return base.Columns[5]; } else { return null; } } set { if (base.Columns.ContainsKey(5)) { base.Columns[5] = value; } else { base.Columns.Add(5, value); } } }
	/// <summary>PID: 4007 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Clientlastconnectiontime_4007 { get { if (base.Columns.ContainsKey(6)) { return base.Columns[6]; } else { return null; } } set { if (base.Columns.ContainsKey(6)) { base.Columns[6] = value; } else { base.Columns.Add(6, value); } } }
	/// <summary>PID: 4007 | Type: read</summary>
	public System.Object Clientlastconnectiontime { get { if (base.Columns.ContainsKey(6)) { return base.Columns[6]; } else { return null; } } set { if (base.Columns.ContainsKey(6)) { base.Columns[6] = value; } else { base.Columns.Add(6, value); } } }
	public ClientsQActionRow() : base(0, 7) { }
	public ClientsQActionRow(System.Object[] oRow) : base(0, 7, oRow) { }
	public static implicit operator ClientsQActionRow(System.Object[] source) { return new ClientsQActionRow(source); }
	public static implicit operator System.Object[](ClientsQActionRow source) { return source.ToObjectArray(); }
}
}
